name: build-translation

on:
  workflow_dispatch:

  pull_request:
    branches: Dev-2.2
    paths:
    - "**.xlf"

jobs:
  build-translation:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Multilingual App Toolkit extension
        uses: microcompiler/install-vsix@db1f973c3d24d1ddc0c38f14d0e1e3a85b2ccb21
        with:
          packagename: 'dts-publisher.mat2022'
      - name: Build solution in Debug configuration
        uses: ./.github/actions/build-solution
        with:
          build-mode: "Debug"
          version: "${{ vars.PRERELEASE_VERSION }}.*"