name: build-debug

on:
  workflow_dispatch:
  pull_request:
    branches: dev-*
    paths:
    - '**.vb'
    - '**.vbproj'

jobs:
  build-debug:
    runs-on: windows-latest
    steps:
      - name: "Get Short SHA"
        run: echo "SHORT_SHA=$("${{ github.sha }}".SubString(0, 8))" >> $env:GITHUB_ENV
      
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Checkout Code
        uses: actions/checkout@v4

      # msbuild cannot handle .vdproj Installer projects, so only build debug for now.
      - name: Build solution
        run: msbuild -t:build -restore -p:Configuration=Debug WinNUT_V2/WinNUT_V2.sln

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ format('WinNUT-Client-debugbuild-{0}', env.SHORT_SHA) }}
          if-no-files-found: error
          path: WinNUT_V2/WinNUT-Client/bin/Debug